import {CREATE_CATEGORIES_TABLE} from "./category";
import {CREATE_CUSTOMER_CARDS_TABLE} from "./customerCard";
import {CREATE_EMPLOYEES_TABLE} from "./employee";
import {CREATE_INVOICES_TABLE} from "./invoice";
import {CREATE_PRODUCTS_TABLE} from "./product";
import {CREATE_SALES_TABLE} from "./sale";
import {CREATE_STORE_PRODUCTS_TABLE} from "./storeProduct";

export const CREATE_TABLES_QUERIES = [
  CREATE_CATEGORIES_TABLE,
  CREATE_CUSTOMER_CARDS_TABLE,
  CREATE_EMPLOYEES_TABLE,
  CREATE_INVOICES_TABLE,
  CREATE_PRODUCTS_TABLE,
  CREATE_SALES_TABLE,
  CREATE_STORE_PRODUCTS_TABLE,
];
